services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: timely-base:latest

  api:
    container_name: api
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    depends_on:
      - base
    image: timely-api:latest
    ports:
      - 4433:4000
    env_file:
      - apps/api/.env.production
    environment:
      - ENVIRONMENT=docker

    healthcheck:
      test: wget localhost:4433/api/v1/health -q -O - > /dev/null 2>&1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  timely-db:
    restart: always
    image: postgres:13
    container_name: timely-db
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    expose:
      - 5433

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: timely-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    ports:
      - "8433:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - timely-db

volumes:
  db-data:
  pgadmin-data:
    driver: local

