version: '3.8'
services:
  timely-db:
    restart: always
    image: postgres:13
    container_name: timely-db
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    expose:
      - 5433

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: timely-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - timely-db

volumes:
  db-data:
  pgadmin-data:
    driver: local

